apis/urls.py
from django.urls import path
from .views import StudentAverageGradesView, GroupAverageGradesView

urlpatterns = [
    path('api/student-average-grades/', StudentAverageGradesView.as_view()),
    path('api/group-average-grades/', GroupAverageGradesView.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('school.urls')),
    path('api/', include('apis.urls')),
]

school/urls.py
from django.urls import path
from .views import TeacherSubjectPageView, StudentGradePageView, HomePageForAdmin


app_name = 'school'

urlpatterns = [
    path('', HomePageForAdmin.as_view(), name="home"),
    path('subjects/', TeacherSubjectPageView.as_view(), name="teacher_subjects"),
    path('grades/', StudentGradePageView.as_view(), name="student_grades"),
]

users/urls.py
from django.urls import path
from .views import LoginPageView, RegisterPageView

app_name = 'users'

urlpatterns = [
    path('login-page/',LoginPageView.as_view(), name='login_page'),
    path('register-page/',RegisterPageView.as_view(), name='register'),

]

school/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models import Avg


class Teacher(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def average_score(self):
        avg_score = Grade.objects.filter(student=self).aggregate(Avg('grade'))['grade__avg']
        return avg_score if avg_score is not None else 0


class Group(models.Model):
    name = models.CharField(max_length=40, unique=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='groups')
    student = models.ManyToManyField(Student, related_name='groups')


class Subject(models.Model):
    name = models.CharField(max_length=100)

    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='subjects')
    students = models.ManyToManyField(Student)

    def __str__(self):
        return self.name


class Grade(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='grades')
    grade = models.SmallIntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True, related_name='grades')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.pk is None and Grade.objects.filter(subject=self.subject, student=self.student).exists():
            raise ValidationError("This student already too his score from this subject")
        super(Grade, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.student}'s grade in {self.subject}: {self.grade}"

school/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.auth_mixins import TeacherRequiredMixin, StudentRequiredMixin,AdminRequiredMixin
from .models import Teacher,Student


class HomePageForAdmin(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'school/home.html')


class TeacherSubjectPageView(TeacherRequiredMixin, View):
    def get(self,request):
        teacher = Teacher.objects.get(name=request.user.username)
        subjects = teacher.subjects.all()
        return render(request, 'school/subjects.html', {"subjects": subjects})


class StudentGradePageView(StudentRequiredMixin, View):
    def get(self,request):
        student = Student.objects.get(name=request.user.username)
        average_score= student.average_score()
        grades = student.grades.all()
        return render(request, 'school/grades.html', {"grades": grades, "average_score":average_score})

school/templates/school/grades.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">

      <div class="row mb-4">
        <div class="col">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">{{user.username}}'s Average Score</h5>
                    <p class="card-text">{{ average_score }}</p>
                </div>
            </div>
        </div>
      </div>

    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Subject ID</th>
      <th scope="col">Subject Name</th>
      <th scope="col">Teacher</th>
      <th scope="col">grade</th>
    </tr>
  </thead>
  <tbody>
  {% for grade in grades %}
    <tr>
      <th scope="row">{{grade.id}}</th>
      <td>{{grade.subject}}</td>
      <td>{{grade.teacher}}</td>
      <td>{{grade.grade}}</td>
    </tr>
  {% endfor %}

  </tbody>
</table>

</div>
{% endblock content %}

school/templates/school/home.html
{% extends 'base.html' %}

{% block content %}
<h1>This is home page</h1>
<ul>
{% if user.user_role == 'admin' %}
    <li><a href="{% url 'users:register' %}">Create teacher or Student</a></li>

{% elif user.user_role == 'student' %}

    <li><a href="{% url 'school:student_grades' %}">Student grades</a></li>

{% elif user.user_role == 'teacher' %}

    <li><a href="{% url 'school:teacher_subjects' %}">Teacher Subjects</a></li>

{% endif %}

</ul>
{% endblock content %}

school/templates/school/student.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

school/templates/school/subjects.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">

      <div class="row mb-4">
        <div class="col">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">{{user.username}}'s Total students </h5>
                    <p class="card-text"></p>
                </div>
            </div>
        </div>
      </div>


    <table class="table">
  <thead>
    <tr>
      <th scope="col">Subject ID</th>
      <th scope="col">Subject Name</th>
      <th scope="col">Teacher</th>
      <th scope="col">number of students</th>
    </tr>
  </thead>
  <tbody>
  {% for sub in subjects %}
    <tr>
      <th scope="row">{{sub.id}}</th>
      <td>{{sub.name}}</td>
      <td>{{sub.teacher}}</td>
      <td>{{sub.students.count}}</td>
    </tr>
  {% endfor %}

  </tbody>
</table>
</div>
{% endblock content %}